apiVersion: v1
kind: Service
metadata:
  name: event-service
  labels:
    app.kubernetes.io/name: event-service
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: event-service
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
