// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/api-keys": {
            "get": {
                "description": "Returns all API keys with their metadata (excluding raw keys)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all API keys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key with admin scope",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.listAPIKeysResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Generates a new API key with specified scopes and metadata. Returns the raw key only once.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key with admin scope",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "API key details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.createAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.createAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request (bad JSON, missing client_id in metadata)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api-keys/{id}": {
            "delete": {
                "description": "Deactivates an API key by setting is_active to false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Revoke an API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key with admin scope",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.revokeAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid API key ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "API key not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/events": {
            "post": {
                "description": "Accepts an event with notifications to be processed asynchronously. Idempotent operation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Submit a new event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key with events:write scope",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for idempotent submission",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Event details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.SubmitEventRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.SubmitEventResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "/api/v1/events/{id}"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request (bad JSON, invalid idempotency key, validation error)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Duplicate event (same idempotency key + type, returns original ID)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}": {
            "get": {
                "description": "Returns the details of a previously submitted event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Retrieve an event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key with events:read scope",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.GetEventResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.GetEventResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "Client identifier from API key metadata",
                    "type": "string",
                    "example": "acme-corp"
                },
                "created_at": {
                    "description": "When the event was created in the system",
                    "type": "string",
                    "example": "2024-01-15T10:30:01Z"
                },
                "id": {
                    "description": "Unique event identifier (UUID)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "occurred_at": {
                    "description": "When the event occurred",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "payload": {
                    "description": "Event-specific data",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "description": "Type of event",
                    "type": "string",
                    "example": "invoice.issued"
                }
            }
        },
        "github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.NotificationDTO": {
            "type": "object",
            "required": [
                "body",
                "channel",
                "recipients"
            ],
            "properties": {
                "body": {
                    "description": "Message body",
                    "type": "string",
                    "example": "Your invoice is ready"
                },
                "channel": {
                    "description": "Notification channel (email, whatsapp)",
                    "type": "string",
                    "example": "email"
                },
                "from": {
                    "description": "Sender address (required for email)",
                    "type": "string",
                    "example": "noreply@example.com"
                },
                "recipients": {
                    "description": "List of recipient addresses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "user@example.com"
                    ]
                },
                "subject": {
                    "description": "Subject line (used for email)",
                    "type": "string",
                    "example": "Invoice #12345"
                }
            }
        },
        "github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.SubmitEventRequest": {
            "type": "object",
            "required": [
                "event_type",
                "notifications"
            ],
            "properties": {
                "event_type": {
                    "description": "Type of event (e.g., invoice.issued, payment.received)",
                    "type": "string",
                    "example": "invoice.issued"
                },
                "notifications": {
                    "description": "List of notifications to send for this event",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.NotificationDTO"
                    }
                },
                "payload": {
                    "description": "Event-specific data (varies by event_type)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_rachelJG_event-notification-service_internal_infrastructure_http_dto.SubmitEventResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique event identifier (UUID)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_infrastructure_http.apiKeyListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "When the key was created",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "id": {
                    "description": "API key ID (UUID)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "description": "Whether the key is active",
                    "type": "boolean",
                    "example": true
                },
                "last_used_at": {
                    "description": "When the key was last used",
                    "type": "string",
                    "example": "2024-01-15T12:00:00Z"
                },
                "metadata": {
                    "description": "Key metadata",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "client_id": "acme-corp"
                    }
                },
                "name": {
                    "description": "Human-readable name",
                    "type": "string",
                    "example": "Acme Corp - Production"
                },
                "scopes": {
                    "description": "List of scopes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "events:write",
                        "events:read"
                    ]
                }
            }
        },
        "internal_infrastructure_http.createAPIKeyRequest": {
            "type": "object",
            "required": [
                "name",
                "scopes"
            ],
            "properties": {
                "metadata": {
                    "description": "Key metadata (client_id is required)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "client_id": "acme-corp",
                        "organization": "Acme Corp"
                    }
                },
                "name": {
                    "description": "Human-readable name for the API key",
                    "type": "string",
                    "example": "Acme Corp - Production"
                },
                "scopes": {
                    "description": "List of scopes (events:write, events:read, admin)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "events:write",
                        "events:read"
                    ]
                }
            }
        },
        "internal_infrastructure_http.createAPIKeyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "API key ID (UUID)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "key": {
                    "description": "Raw API key (returned only on creation)",
                    "type": "string",
                    "example": "abc123...xyz"
                },
                "metadata": {
                    "description": "Key metadata",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "client_id": "acme-corp"
                    }
                },
                "name": {
                    "description": "Human-readable name",
                    "type": "string",
                    "example": "Acme Corp - Production"
                },
                "scopes": {
                    "description": "List of scopes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "events:write",
                        "events:read"
                    ]
                }
            }
        },
        "internal_infrastructure_http.listAPIKeysResponse": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http.apiKeyListItem"
                    }
                }
            }
        },
        "internal_infrastructure_http.revokeAPIKeyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "api key revoked"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key authentication. Use format: \"your-api-key-here\"",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Event Notification Service API",
	Description:      "A scalable event notification service supporting multiple channels (email, WhatsApp). Events are submitted with notifications and processed asynchronously.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
